// =============================================================================
// AnimaI T2I v2 — Prompt Builder (standalone, file:// safe)
// Data: window.PROMPTS_DATA / window.MODEL_PRESETS (generated by build.py)
// =============================================================================
'use strict';

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------
const CHAR_SCOPED_SLOTS = new Set([
    'subject', 'hair', 'hair_color', 'expression', 'clothing',
    'accessories', 'pose', 'situation',
    'n_nsfw', 'n_body_type', 'n_expression', 'n_accessories', 'n_pose', 'n_situation',
]);

const LS = {
    favorites: 'anima.favorites',
    presets: 'anima.presets',
    settings: 'anima.settings',
    theme: 'theme',
};

const state = {
    // model & settings
    modelId: 'illustrious',
    presets: [],           // editable copies of MODEL_PRESETS
    nsfwMode: false,
    ratingAuto: true,      // insert safe/nsfw automatically
    qualityAuto: true,     // append preset quality/era tags automatically
    multiChar: false,
    activeSlot: 0,         // 0 = shared/single, 1..3 = character slots

    // selections: Map(prompt -> { weight, locked, cat })
    slots: [new Map(), new Map(), new Map(), new Map()], // [0]=shared, [1..3]=chars
    negativeTags: new Map(),

    // runtime
    tagElements: new Map(),   // `${catId}::${prompt}` -> button el
    favorites: [],
};

// ---------------------------------------------------------------------------
// Persistence helpers
// ---------------------------------------------------------------------------
function loadJSON(key, fallback) {
    try {
        const raw = localStorage.getItem(key);
        return raw ? JSON.parse(raw) : fallback;
    } catch (e) {
        return fallback;
    }
}

function saveJSON(key, value) {
    try {
        localStorage.setItem(key, JSON.stringify(value));
    } catch (e) {
        console.error('localStorage save failed', e);
    }
}

function currentPreset() {
    if (!state.presets || state.presets.length === 0) {
        state.presets = (window.MODEL_PRESETS || []).map(p => ({ ...p }));
    }
    return state.presets.find(p => p.id === state.modelId) || state.presets[0];
}

// ---------------------------------------------------------------------------
// Token estimation (CLIP ~77 token limit approximation)
// ---------------------------------------------------------------------------
function countTokens(text) {
    if (!text) return 0;
    let total = 0;
    for (const rawTag of text.split(',')) {
        const tag = rawTag.trim();
        if (!tag) continue;
        total += 1; // comma overhead
        const words = tag.split(/[\s_]+/).filter(Boolean);
        for (const w of words) {
            const clean = w.replace(/[():"']/g, '');
            if (!clean) continue;
            total += clean.length <= 5 ? 1 : 2;
        }
    }
    return total;
}

// ---------------------------------------------------------------------------
// Data access
// ---------------------------------------------------------------------------
function allCategories() {
    const d = window.PROMPTS_DATA;
    return [...d.sfw, ...d.nsfw, ...d.negative];
}

function categoryById(id) {
    return allCategories().find(c => c.id === id);
}

function findTagCategory(prompt) {
    for (const c of allCategories()) {
        if (c.tags.some(t => t.prompt === prompt)) return c;
    }
    return null;
}

// ---------------------------------------------------------------------------
// Selection logic
// ---------------------------------------------------------------------------
function selectionTarget(cat) {
    // negative section -> negative pool
    if (cat && cat.section === 'negative') return state.negativeTags;
    // char-scoped category in multi-char mode -> active character slot
    if (state.multiChar && cat && CHAR_SCOPED_SLOTS.has(cat.id) && state.activeSlot > 0) {
        return state.slots[state.activeSlot];
    }
    return state.slots[0];
}

function toggleTag(cat, prompt) {
    const target = selectionTarget(cat);
    const key = `${cat.id}::${prompt}`;
    if (target.has(prompt)) {
        target.delete(prompt);
    } else {
        target.set(prompt, { weight: 1.0, locked: false, cat: cat.id });
    }
    const btn = state.tagElements.get(key);
    if (btn) btn.classList.toggle('active', target.has(prompt));
    refreshOutputs();
}

function removeTag(pool, prompt) {
    const meta = pool.get(prompt);
    pool.delete(prompt);
    if (meta) {
        const btn = state.tagElements.get(`${meta.cat}::${prompt}`);
        if (btn) btn.classList.remove('active');
    }
    refreshOutputs();
}

function setWeight(pool, prompt, delta) {
    const meta = pool.get(prompt);
    if (!meta) return;
    meta.weight = Math.round((meta.weight + delta) * 10) / 10;
    if (meta.weight < 0.5) meta.weight = 0.5;
    if (meta.weight > 1.9) meta.weight = 1.9;
    refreshOutputs();
}

function toggleLock(pool, prompt) {
    const meta = pool.get(prompt);
    if (!meta) return;
    meta.locked = !meta.locked;
    renderSelectedChips();
}

// ---------------------------------------------------------------------------
// Prompt assembly engine
// ---------------------------------------------------------------------------
function applyWeight(prompt, meta) {
    if (meta && meta.weight && meta.weight !== 1.0) {
        return `(${prompt}:${meta.weight.toFixed(1)})`;
    }
    return prompt;
}

function collectSlotTags(slotMap, slotName, preset) {
    // returns array of {prompt, meta} belonging to slotName
    const out = [];
    slotMap.forEach((meta, prompt) => {
        const cat = categoryById(meta.cat);
        const slot = cat ? cat.slot : 'composition';
        if (slot === slotName) out.push({ prompt, meta });
    });
    return out;
}

function autoRatingTag() {
    if (!state.ratingAuto || !currentPreset().ratingAuto) return null;
    return state.nsfwMode ? 'nsfw' : 'safe';
}

function autoQualityTags() {
    if (!state.qualityAuto) return [];
    const p = currentPreset();
    return p.quality || [];
}

function autoEraTag() {
    if (!state.qualityAuto) return null;
    const p = currentPreset();
    return p.era || null;
}

function assemblePositive() {
    const preset = currentPreset();
    const template = preset.template || [];

    // --- single / shared pool ---
    const sharedPool = state.slots[0];
    const groups = {}; // slotName -> [string]
    const emitted = new Set(); // final-prompt level tag dedupe

    for (const slotName of template) groups[slotName] = [];

    // distribute selected tags into slots (keep selection order inside slot)
    sharedPool.forEach((meta, prompt) => {
        const cat = categoryById(meta.cat);
        const slot = cat ? cat.slot : 'composition';
        if (!groups[slot]) groups[slot] = [];
        const parts = prompt.split(',').map(s => s.trim()).filter(Boolean);
        const kept = [];
        for (const p of parts) {
            const k = p.toLowerCase();
            if (emitted.has(k)) continue;
            emitted.add(k);
            kept.push(p);
        }
        if (kept.length === 0) return; // fully duplicate entry
        groups[slot].push(applyWeight(kept.join(', '), meta));
    });

    // auto rating
    const rating = autoRatingTag();
    if (rating && !groups.rating.includes(rating)) groups.rating.unshift(rating);
    // auto quality
    for (const q of autoQualityTags()) {
        if (!groups.quality.includes(q)) groups.quality.push(q);
    }
    // auto era
    const era = autoEraTag();
    if (era && !groups.era.includes(era)) groups.era.push(era);

    let result = [];
    if (!state.multiChar) {
        result = template.flatMap(s => groups[s] || []);
    } else {
        // multi-character: subject & rating first, then BREAK-separated chars,
        // then remaining shared slots in template order
        result.push(...(groups.subject || []));
        result.push(...(groups.rating || []));
        result.push(...(groups.character || []));
        const charBlocks = [];
        const charEmitted = new Set(emitted); // shared tags already emitted
        for (let i = 1; i <= 3; i++) {
            const pool = state.slots[i];
            if (pool.size === 0) continue;
            const charGroups = {};
            for (const slotName of template) charGroups[slotName] = [];
            pool.forEach((meta, prompt) => {
                const cat = categoryById(meta.cat);
                const slot = cat ? cat.slot : 'composition';
                if (!charGroups[slot]) charGroups[slot] = [];
                const parts = prompt.split(',').map(s => s.trim()).filter(Boolean);
                const kept = [];
                for (const p of parts) {
                    const k = p.toLowerCase();
                    if (charEmitted.has(k)) continue;
                    charEmitted.add(k);
                    kept.push(p);
                }
                if (kept.length === 0) return;
                charGroups[slot].push(applyWeight(kept.join(', '), meta));
            });
            const block = template.flatMap(s => charGroups[s] || []);
            if (block.length) charBlocks.push(block.join(', '));
        }
        if (charBlocks.length) result.push(charBlocks.join(', BREAK, '));
        for (const s of template) {
            if (['subject', 'character', 'rating'].includes(s)) continue;
            result.push(...(groups[s] || []));
        }
    }
    return result.filter(Boolean).join(', ');
}

function assembleNegative() {
    const out = [];
    const emittedNeg = new Set();
    state.negativeTags.forEach((meta, prompt) => {
        const parts = prompt.split(',').map(s => s.trim()).filter(Boolean);
        const seenLocal = new Set();
        const kept = parts.filter(p => {
            const k = p.toLowerCase();
            if (seenLocal.has(k) || emittedNeg.has(k)) return false;
            seenLocal.add(k);
            return true;
        });
        if (kept.length === 0) return;
        kept.forEach(p => emittedNeg.add(p.toLowerCase()));
        out.push(applyWeight(kept.join(', '), meta));
    });
    return out.join(', ');
}

// ---------------------------------------------------------------------------
// Rendering: categories
// ---------------------------------------------------------------------------
function renderCategories() {
    const d = window.PROMPTS_DATA;
    const sfwEl = document.getElementById('sfw-categories');
    const nsfwEl = document.getElementById('nsfw-categories');
    const negEl = document.getElementById('negative-categories');
    state.tagElements.clear();
    renderCategoryList(d.sfw, sfwEl, false, true);
    renderCategoryList(d.nsfw, nsfwEl, false, false);
    renderCategoryList(d.negative, negEl, true, true);
}

function renderCategoryList(categories, containerEl, isNegative, defaultOpenFirst) {
    containerEl.innerHTML = '';
    if (!categories || categories.length === 0) {
        containerEl.innerHTML = '<div class="loading">データがありません。</div>';
        return;
    }
    const filter = (document.getElementById('tag-search-input')?.value || '').toLowerCase();

    categories.forEach((cat, index) => {
        const card = document.createElement('div');
        card.className = `category-card${defaultOpenFirst && index === 0 ? '' : ' collapsed'}`;
        card.dataset.cat = cat.id;

        const title = document.createElement('div');
        title.className = 'category-title';
        title.textContent = `${cat.name} (${cat.tags.length})`;
        title.addEventListener('click', () => card.classList.toggle('collapsed'));

        const body = document.createElement('div');
        body.className = 'category-body';
        const inner = document.createElement('div');
        inner.className = 'category-body-inner';

        let visible = 0;
        cat.tags.forEach(item => {
            if (filter && !item.japanese.toLowerCase().includes(filter)
                && !item.prompt.toLowerCase().includes(filter)) return;
            visible++;
            inner.appendChild(createTagElement(cat, item));
        });

        if (filter && visible === 0) {
            const none = document.createElement('div');
            none.className = 'loading';
            none.textContent = '一致するタグなし';
            inner.appendChild(none);
        }

        body.appendChild(inner);
        card.appendChild(title);
        card.appendChild(body);
        containerEl.appendChild(card);
    });
}

function createTagElement(cat, item) {
    const btn = document.createElement('button');
    btn.className = 'prompt-tag';

    const jp = document.createElement('span');
    jp.className = 'jp-name';
    jp.textContent = item.japanese;

    const en = document.createElement('span');
    en.className = 'en-name';
    en.textContent = item.prompt;

    btn.appendChild(jp);
    btn.appendChild(en);

    // restore active state
    const isActive = [...(selectionTarget(cat).keys())].includes(item.prompt)
        || (cat.section !== 'negative'
            && state.slots.some(pool => pool.has(item.prompt)));
    if (isActive) btn.classList.add('active');

    btn.addEventListener('click', (e) => {
        e.stopPropagation();
        toggleTag(cat, item.prompt);
    });

    state.tagElements.set(`${cat.id}::${item.prompt}`, btn);
    return btn;
}

// ---------------------------------------------------------------------------
// Rendering: selected chips (with weight / lock / remove)
// ---------------------------------------------------------------------------
function renderSelectedChips() {
    const wrap = document.getElementById('selected-chips');
    if (!wrap) return;
    wrap.innerHTML = '';

    const mkChips = (pool, label) => {
        if (pool.size === 0) return;
        const group = document.createElement('div');
        group.className = 'chip-group';
        const gLabel = document.createElement('div');
        gLabel.className = 'chip-group-label';
        gLabel.textContent = label;
        group.appendChild(gLabel);

        pool.forEach((meta, prompt) => {
            const chip = document.createElement('div');
            chip.className = `chip${meta.locked ? ' locked' : ''}`;

            const name = document.createElement('span');
            name.className = 'chip-name';
            name.textContent = prompt;
            name.title = prompt;
            chip.appendChild(name);

            if (meta.cat !== 'manual') {
                const minus = document.createElement('button');
                minus.textContent = '−';
                minus.title = '重み -0.1';
                minus.addEventListener('click', () => setWeight(pool, prompt, -0.1));
                const w = document.createElement('span');
                w.className = 'chip-weight';
                w.textContent = meta.weight.toFixed(1);
                const plus = document.createElement('button');
                plus.textContent = '+';
                plus.title = '重み +0.1';
                plus.addEventListener('click', () => setWeight(pool, prompt, +0.1));
                chip.appendChild(minus);
                chip.appendChild(w);
                chip.appendChild(plus);
            }

            const lock = document.createElement('button');
            lock.textContent = meta.locked ? '🔒' : '🔓';
            lock.title = 'ランダム生成時に固定';
            lock.addEventListener('click', () => toggleLock(pool, prompt));
            chip.appendChild(lock);

            const del = document.createElement('button');
            del.textContent = '×';
            del.title = '削除';
            del.addEventListener('click', () => removeTag(pool, prompt));
            chip.appendChild(del);

            group.appendChild(chip);
        });
        wrap.appendChild(group);
    };

    if (state.multiChar) {
        mkChips(state.slots[0], '共通');
        for (let i = 1; i <= 3; i++) {
            if (state.slots[i].size > 0) mkChips(state.slots[i], `キャラ${i}`);
        }
    } else {
        mkChips(state.slots[0], '選択中');
    }
    mkChips(state.negativeTags, 'ネガティブ');
}

// ---------------------------------------------------------------------------
// Rendering: outputs & token counters
// ---------------------------------------------------------------------------
function refreshOutputs() {
    const pos = assemblePositive();
    const neg = assembleNegative();
    document.getElementById('positive-prompt-output').value = pos;
    document.getElementById('negative-prompt-output').value = neg;

    const posTok = countTokens(pos);
    const negTok = countTokens(neg);
    const posEl = document.getElementById('pos-token-count');
    const negEl = document.getElementById('neg-token-count');
    posEl.textContent = `約 ${posTok} / 75 トークン`;
    posEl.className = 'token-count' + (posTok > 75 ? ' over' : posTok > 60 ? ' warn' : '');
    negEl.textContent = `約 ${negTok} / 75 トークン`;
    negEl.className = 'token-count' + (negTok > 75 ? ' over' : negTok > 60 ? ' warn' : '');

    // model badge on positive card
    const badge = document.getElementById('model-badge');
    if (badge) badge.textContent = currentPreset().name;

    renderSelectedChips();
}

// ---------------------------------------------------------------------------
// Random generation (lock-aware)
// ---------------------------------------------------------------------------
const RANDOM_CATEGORIES = [
    'subject', 'hair', 'hair_color', 'expression', 'clothing',
    'accessories', 'pose', 'situation', 'composition', 'background',
    'background_style', 'effect', 'art_style', 'era',
    'n_nsfw', 'n_body_type', 'n_expression', 'n_accessories', 'n_pose', 'n_situation',
];

function randomize() {
    const pools = state.multiChar
        ? (state.activeSlot > 0 ? [state.slots[state.activeSlot]] : [state.slots[0]])
        : [state.slots[0]];

    for (const catId of RANDOM_CATEGORIES) {
        const cat = categoryById(catId);
        if (!cat) continue;
        if (catId.startsWith('n_') && !state.nsfwMode) continue;
        if (!catId.startsWith('n_') && (cat.section === 'negative')) continue;

        const pool = (state.multiChar && CHAR_SCOPED_SLOTS.has(catId) && state.activeSlot > 0)
            ? state.slots[state.activeSlot] : pools[0];
        if (!pool) continue;

        // keep locked tags of this category
        const locked = [];
        pool.forEach((meta, prompt) => {
            if (meta.cat === catId) {
                if (meta.locked) locked.push({ prompt, meta });
                pool.delete(prompt);
                const btn = state.tagElements.get(`${catId}::${prompt}`);
                if (btn) btn.classList.remove('active');
            }
        });

        const skipChance = ['accessories', 'effect', 'art_style', 'era', 'situation'].includes(catId) ? 0.35 : 0.1;
        const mustPick = catId === 'subject' || catId === 'hair' || catId === 'expression';
        if (!mustPick && Math.random() < skipChance) {
            locked.forEach(l => pool.set(l.prompt, l.meta));
            continue;
        }
        const pick = cat.tags[Math.floor(Math.random() * cat.tags.length)];
        if (pick) {
            pool.set(pick.prompt, { weight: 1.0, locked: false, cat: catId });
            const btn = state.tagElements.get(`${catId}::${pick.prompt}`);
            if (btn) btn.classList.add('active');
        }
        locked.forEach(l => pool.set(l.prompt, l.meta));
    }
    refreshOutputs();
}

// ---------------------------------------------------------------------------
// Favorites (localStorage)
// ---------------------------------------------------------------------------
function serializeSelection() {
    const ser = m => {
        const o = {};
        m.forEach((meta, prompt) => o[prompt] = meta);
        return o;
    };
    return {
        modelId: state.modelId,
        nsfwMode: state.nsfwMode,
        multiChar: state.multiChar,
        ratingAuto: state.ratingAuto,
        qualityAuto: state.qualityAuto,
        slots: state.slots.map(ser),
        negative: ser(state.negativeTags),
    };
}

function restoreSelection(data) {
    const deser = o => {
        const m = new Map();
        Object.entries(o || {}).forEach(([prompt, meta]) => m.set(prompt, meta));
        return m;
    };
    state.modelId = data.modelId || state.modelId;
    state.nsfwMode = !!data.nsfwMode;
    state.multiChar = !!data.multiChar;
    state.ratingAuto = data.ratingAuto !== false;
    state.qualityAuto = data.qualityAuto !== false;
    state.slots = [0, 1, 2, 3].map(i => deser(data.slots ? data.slots[i] : {}));
    state.negativeTags = deser(data.negative);
    syncControlsFromState();
    renderCategories();
    refreshOutputs();
}

function renderFavorites() {
    const listEl = document.getElementById('favorites-list');
    if (!listEl) return;
    listEl.innerHTML = '';
    if (state.favorites.length === 0) {
        listEl.innerHTML = '<div class="no-favorites">保存されたお気に入りはまだありません。</div>';
        return;
    }
    state.favorites.forEach(preset => {
        const item = document.createElement('div');
        item.className = 'favorite-item';

        const content = document.createElement('div');
        content.className = 'favorite-item-content';
        const nameEl = document.createElement('div');
        nameEl.className = 'favorite-item-name';
        nameEl.textContent = '⭐ ' + preset.name;
        const metaEl = document.createElement('div');
        metaEl.className = 'favorite-item-meta';
        const totalTags = (preset.data?.slots || []).reduce((a, s) => a + Object.keys(s || {}).length, 0)
            + Object.keys(preset.data?.negative || {}).length;
        metaEl.innerHTML = `<span>タグ: ${totalTags}</span> <span>${preset.data?.modelId || ''}</span>`;
        content.appendChild(nameEl);
        content.appendChild(metaEl);

        item.addEventListener('click', () => restoreSelection(preset.data));

        const actions = document.createElement('div');
        actions.className = 'favorite-item-actions';
        const deleteBtn = document.createElement('button');
        deleteBtn.className = 'fav-delete-btn';
        deleteBtn.innerHTML = '🗑️';
        deleteBtn.title = '削除';
        deleteBtn.addEventListener('click', async (e) => {
            e.stopPropagation();
            if (confirm(`お気に入り「${preset.name}」を削除してもよろしいですか？`)) {
                state.favorites = state.favorites.filter(f => f.name !== preset.name);
                saveJSON(LS.favorites, state.favorites);
                renderFavorites();
            }
        });
        actions.appendChild(deleteBtn);

        item.appendChild(content);
        item.appendChild(actions);
        listEl.appendChild(item);
    });
}

function saveFavorite() {
    const inputEl = document.getElementById('favorite-name-input');
    const name = inputEl.value.trim();
    const hasAny = state.slots.some(s => s.size > 0) || state.negativeTags.size > 0;
    if (!name) { alert('お気に入りの名前を入力してください。'); return; }
    if (!hasAny) { alert('プロンプトが選択されていません。'); return; }
    if (state.favorites.some(f => f.name === name)) {
        if (!confirm(`「${name}」を上書きしますか？`)) return;
        state.favorites = state.favorites.filter(f => f.name !== name);
    }
    state.favorites.push({ name, data: serializeSelection() });
    saveJSON(LS.favorites, state.favorites);
    inputEl.value = '';
    renderFavorites();
}

function exportFavorites() {
    const blob = new Blob([JSON.stringify(state.favorites, null, 2)], { type: 'application/json' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'animaI-favorites.json';
    a.click();
    URL.revokeObjectURL(a.href);
}

function importFavorites(file) {
    const reader = new FileReader();
    reader.onload = () => {
        try {
            const imported = JSON.parse(reader.result);
            if (!Array.isArray(imported)) throw new Error('format');
            const names = new Set(state.favorites.map(f => f.name));
            for (const f of imported) {
                if (!f || !f.name || !f.data) continue;
                if (names.has(f.name)) f.name = f.name + ' (imported)';
                state.favorites.push(f);
            }
            saveJSON(LS.favorites, state.favorites);
            renderFavorites();
        } catch (e) {
            alert('読み込みに失敗しました。JSON形式が正しくありません。');
        }
    };
    reader.readAsText(file);
}

// ---------------------------------------------------------------------------
// Preset editor modal
// ---------------------------------------------------------------------------
function openPresetModal() {
    const modal = document.getElementById('preset-modal');
    const list = document.getElementById('preset-editor-list');
    list.innerHTML = '';
    state.presets.forEach(p => {
        const row = document.createElement('div');
        row.className = 'preset-editor-row';
        row.innerHTML = `
            <div class="preset-editor-name">${p.name}</div>
            <label>品質タグ（カンマ区切り）
                <input type="text" data-field="quality" value="${(p.quality || []).join(', ')}">
            </label>
            <label>年代タグ（空欄で無効）
                <input type="text" data-field="era" value="${p.era || ''}">
            </label>
            <label>レーティング自動挿入
                <input type="checkbox" data-field="ratingAuto" ${p.ratingAuto ? 'checked' : ''}>
            </label>
            <label>推奨ネガティブ（初期値）
                <textarea data-field="negativeBase" rows="2">${p.negativeBase || ''}</textarea>
            </label>
        `;
        row.querySelectorAll('[data-field]').forEach(input => {
            input.addEventListener('change', () => {
                const f = input.dataset.field;
                if (f === 'quality') p.quality = input.value.split(',').map(s => s.trim()).filter(Boolean);
                else if (f === 'era') p.era = input.value.trim() || null;
                else if (f === 'ratingAuto') p.ratingAuto = input.checked;
                else if (f === 'negativeBase') p.negativeBase = input.value.trim();
                saveJSON(LS.presets, state.presets);
                refreshOutputs();
            });
        });
        list.appendChild(row);
    });
    modal.style.display = 'flex';
}

function closePresetModal() {
    document.getElementById('preset-modal').style.display = 'none';
}

// ---------------------------------------------------------------------------
// Controls sync
// ---------------------------------------------------------------------------
function syncControlsFromState() {
    const modelSelect = document.getElementById('model-select');
    if (modelSelect) modelSelect.value = state.modelId;
    const nsfwToggle = document.getElementById('nsfw-toggle');
    if (nsfwToggle) nsfwToggle.checked = state.nsfwMode;
    const multiToggle = document.getElementById('multichar-toggle');
    if (multiToggle) multiToggle.checked = state.multiChar;
    const ratingToggle = document.getElementById('rating-auto-toggle');
    if (ratingToggle) ratingToggle.checked = state.ratingAuto;
    const qualityToggle = document.getElementById('quality-auto-toggle');
    if (qualityToggle) qualityToggle.checked = state.qualityAuto;
    updateNsfwUI();
    updateCharSlotUI();
}

function updateNsfwUI() {
    const nsfwTabBtn = document.getElementById('nsfw-tab-btn');
    const posBadge = document.querySelector('.positive-badge');
    if (nsfwTabBtn) nsfwTabBtn.style.display = state.nsfwMode ? 'inline-block' : 'none';
    if (posBadge) {
        posBadge.textContent = state.nsfwMode ? 'NSFW Mode' : 'SFW';
        posBadge.className = 'badge positive-badge' + (state.nsfwMode ? ' nsfw-mode' : '');
    }
    if (state.nsfwMode === false && document.getElementById('nsfw-tab-btn')?.classList.contains('active')) {
        document.querySelector('.tab-btn[data-tab="sfw"]')?.click();
    }
}

function updateCharSlotUI() {
    const bar = document.getElementById('char-slot-bar');
    if (!bar) return;
    bar.style.display = state.multiChar ? 'flex' : 'none';
    bar.querySelectorAll('.char-slot-pill').forEach(pill => {
        pill.classList.toggle('active', Number(pill.dataset.slot) === state.activeSlot);
    });
}

function updatePresetSelectOptions() {
    const sel = document.getElementById('model-select');
    if (!sel) return;
    sel.innerHTML = '';
    state.presets.forEach(p => {
        const opt = document.createElement('option');
        opt.value = p.id;
        opt.textContent = p.name;
        sel.appendChild(opt);
    });
    sel.value = state.modelId;
}

function saveSettings() {
    saveJSON(LS.settings, {
        modelId: state.modelId,
        nsfwMode: state.nsfwMode,
        ratingAuto: state.ratingAuto,
        qualityAuto: state.qualityAuto,
        multiChar: state.multiChar,
    });
}

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------
document.addEventListener('DOMContentLoaded', () => {
    // ----- load persisted state -----
    state.presets = loadJSON(LS.presets, null) || (window.MODEL_PRESETS || []).map(p => ({ ...p }));
    const settings = loadJSON(LS.settings, {});
    state.modelId = settings.modelId || (state.presets[0] && state.presets[0].id) || 'illustrious';
    state.nsfwMode = !!settings.nsfwMode;
    state.ratingAuto = settings.ratingAuto !== false;
    state.qualityAuto = settings.qualityAuto !== false;
    state.multiChar = !!settings.multiChar;
    state.favorites = loadJSON(LS.favorites, []);

    // ----- render static UI -----
    updatePresetSelectOptions();
    renderCategories();
    renderFavorites();
    syncControlsFromState();
    refreshOutputs();

    // ----- tabs -----
    const tabBtns = document.querySelectorAll('.tab-btn');
    const tabPanels = document.querySelectorAll('.tab-panel');
    tabBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            tabBtns.forEach(b => b.classList.remove('active'));
            tabPanels.forEach(p => p.classList.remove('active'));
            btn.classList.add('active');
            document.getElementById(`panel-${btn.getAttribute('data-tab')}`).classList.add('active');
        });
    });

    // ----- search -----
    const searchInput = document.getElementById('tag-search-input');
    if (searchInput) {
        searchInput.addEventListener('input', () => renderCategories());
        document.getElementById('tag-search-clear')?.addEventListener('click', () => {
            searchInput.value = '';
            renderCategories();
        });
    }

    // ----- model select -----
    document.getElementById('model-select')?.addEventListener('change', (e) => {
        state.modelId = e.target.value;
        saveSettings();
        refreshOutputs();
    });

    // ----- toggles -----
    document.getElementById('nsfw-toggle')?.addEventListener('change', (e) => {
        state.nsfwMode = e.target.checked;
        saveSettings();
        updateNsfwUI();
        refreshOutputs();
    });
    document.getElementById('multichar-toggle')?.addEventListener('change', (e) => {
        state.multiChar = e.target.checked;
        state.activeSlot = 0;
        saveSettings();
        updateCharSlotUI();
        refreshOutputs();
    });
    document.getElementById('rating-auto-toggle')?.addEventListener('change', (e) => {
        state.ratingAuto = e.target.checked;
        saveSettings();
        refreshOutputs();
    });
    document.getElementById('quality-auto-toggle')?.addEventListener('change', (e) => {
        state.qualityAuto = e.target.checked;
        saveSettings();
        refreshOutputs();
    });

    // ----- character slot pills -----
    document.querySelectorAll('.char-slot-pill').forEach(pill => {
        pill.addEventListener('click', () => {
            state.activeSlot = Number(pill.dataset.slot);
            updateCharSlotUI();
        });
    });

    // ----- random -----
    document.getElementById('random-btn')?.addEventListener('click', randomize);

    // ----- preset modal -----
    document.getElementById('preset-edit-btn')?.addEventListener('click', openPresetModal);
    document.getElementById('preset-modal-close')?.addEventListener('click', closePresetModal);
    document.getElementById('preset-modal')?.addEventListener('click', (e) => {
        if (e.target.id === 'preset-modal') closePresetModal();
    });

    // ----- recommended negative quick-add -----
    document.getElementById('add-recommended-negative-btn')?.addEventListener('click', () => {
        const base = currentPreset().negativeBase;
        if (!base) { alert('このプリセットには推奨ネガティブが設定されていません。'); return; }
        base.split(',').map(s => s.trim()).filter(Boolean).forEach(t => {
            if (!state.negativeTags.has(t)) {
                state.negativeTags.set(t, { weight: 1.0, locked: false, cat: 'manual' });
            }
        });
        refreshOutputs();
    });

    // ----- manual tag additions -----
    const handleManualAdd = (inputId, isNegative) => {
        const inputEl = document.getElementById(inputId);
        const text = inputEl.value.trim();
        if (!text) return;
        const pool = isNegative ? state.negativeTags
            : (state.multiChar && state.activeSlot > 0 ? state.slots[state.activeSlot] : state.slots[0]);
        text.split(',').map(t => t.trim()).filter(Boolean).forEach(tag => {
            if (!pool.has(tag)) pool.set(tag, { weight: 1.0, locked: false, cat: 'manual' });
        });
        inputEl.value = '';
        refreshOutputs();
    };
    document.getElementById('add-manual-positive-btn')?.addEventListener('click', () => handleManualAdd('manual-positive-input', false));
    document.getElementById('manual-positive-input')?.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') handleManualAdd('manual-positive-input', false);
    });
    document.getElementById('add-manual-negative-btn')?.addEventListener('click', () => handleManualAdd('manual-negative-input', true));
    document.getElementById('manual-negative-input')?.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') handleManualAdd('manual-negative-input', true);
    });

    // ----- favorites -----
    document.getElementById('save-favorite-btn')?.addEventListener('click', saveFavorite);
    document.getElementById('favorite-name-input')?.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') saveFavorite();
    });
    document.getElementById('export-favorites-btn')?.addEventListener('click', exportFavorites);
    document.getElementById('import-favorites-btn')?.addEventListener('click', () => {
        document.getElementById('import-favorites-file')?.click();
    });
    document.getElementById('import-favorites-file')?.addEventListener('change', (e) => {
        if (e.target.files && e.target.files[0]) importFavorites(e.target.files[0]);
        e.target.value = '';
    });

    // ----- clear buttons -----
    document.getElementById('clear-positive-btn')?.addEventListener('click', () => {
        for (let i = 0; i <= 3; i++) state.slots[i].clear();
        state.tagElements.forEach(btn => {
            if (!btn.closest('#panel-negative')) btn.classList.remove('active');
        });
        refreshOutputs();
    });
    document.getElementById('clear-negative-btn')?.addEventListener('click', () => {
        state.negativeTags.clear();
        state.tagElements.forEach(btn => {
            if (btn.closest('#panel-negative')) btn.classList.remove('active');
        });
        refreshOutputs();
    });

    // ----- copy -----
    const handleCopy = (btnEl, textValue) => {
        if (!textValue) return;
        navigator.clipboard.writeText(textValue).then(() => {
            btnEl.classList.add('copied');
            const copyText = btnEl.querySelector('.copy-text');
            const successText = btnEl.querySelector('.copy-success-text');
            copyText.style.display = 'none';
            successText.style.display = 'inline';
            setTimeout(() => {
                btnEl.classList.remove('copied');
                copyText.style.display = 'inline';
                successText.style.display = 'none';
            }, 2000);
        }).catch(err => console.error('copy failed', err));
    };
    document.getElementById('copy-positive-btn')?.addEventListener('click', (e) => {
        handleCopy(e.currentTarget, document.getElementById('positive-prompt-output').value);
    });
    document.getElementById('copy-negative-btn')?.addEventListener('click', (e) => {
        handleCopy(e.currentTarget, document.getElementById('negative-prompt-output').value);
    });

    // ----- theme -----
    const themeToggleBtn = document.getElementById('theme-toggle-btn');
    const sunIcon = themeToggleBtn.querySelector('.theme-icon-sun');
    const moonIcon = themeToggleBtn.querySelector('.theme-icon-moon');
    const applyTheme = (theme) => {
        document.documentElement.setAttribute('data-theme', theme);
        localStorage.setItem(LS.theme, theme);
        sunIcon.style.display = theme === 'light' ? 'none' : 'inline';
        moonIcon.style.display = theme === 'light' ? 'inline' : 'none';
    };
    applyTheme(localStorage.getItem(LS.theme) || 'dark');
    themeToggleBtn.addEventListener('click', () => {
        const cur = document.documentElement.getAttribute('data-theme');
        applyTheme(cur === 'dark' ? 'light' : 'dark');
    });
});
